#!/bin/bash

if [ $# == 0 ];then
	echo "Usage:$0 [start|stop|restart]"
	exit -1
fi

if [ $1 == 'start' ];then
	uwsgi --ini pj_server_uwsgi.ini &
fi

if [ $1 == 'stop' ];then
	pid=`cat ./uwsgi/uwsgi.pid`
	kill -9 $pid
fi

if [ $1 == 'restart' ];then
	pid=`cat ./uwsgi/uwsgi.pid`
	kill -9 $pid
	uwsgi --ini pj_server_uwsgi.ini &
fi
