# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mana_user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=32, verbose_name='\u5bc6\u7801')),
                ('level', models.IntegerField(verbose_name='\u6743\u9650')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'mana_user',
                'verbose_name': '\u7ba1\u7406\u5458\u8d26\u6237',
            },
        ),
        migrations.CreateModel(
            name='paijiu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('paixing', models.CharField(max_length=32)),
                ('score', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'paijiu',
                'verbose_name': '\u724c\u4e5d\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('player_id', models.CharField(max_length=32, verbose_name='\u5fae\u4fe1ID')),
                ('phone_num', models.CharField(max_length=20, verbose_name='\u624b\u673a\u53f7')),
                ('nick_name', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1\u540d\u79f0')),
                ('head_img_url', models.CharField(max_length=256)),
                ('sex', models.IntegerField()),
                ('fangka_num', models.IntegerField(verbose_name='\u623f\u5361\u6570\u91cf')),
                ('round_num', models.IntegerField(verbose_name='\u6e38\u620f\u5c40\u6570')),
                ('all_score', models.IntegerField(verbose_name='\u6e38\u620f\u5f97\u5206')),
                ('win_num', models.IntegerField(verbose_name='\u80dc\u5229\u5c40\u6570')),
                ('lose_num', models.IntegerField(verbose_name='\u5931\u8d25\u5c40\u6570')),
                ('fangka_history', models.IntegerField(verbose_name='\u8d2d\u4e70\u623f\u5361\u603b\u6570')),
                ('invalid_fangka', models.IntegerField(verbose_name='\u65e0\u6548\u7684\u623f\u5361')),
                ('gonghui_id', models.CharField(max_length=12, verbose_name='\u5de5\u4f1aID')),
                ('loginCount', models.IntegerField()),
                ('createTime', models.BigIntegerField()),
                ('continueLoginDays', models.IntegerField()),
                ('lastLoginTime', models.BigIntegerField()),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'player',
                'verbose_name': '\u73a9\u5bb6\u4fe1\u606f\u8868',
            },
        ),
    ]
